FROM node:24.5-slim

WORKDIR /app

COPY ./package.json .
COPY ./package-lock.json .
COPY ./frontend/package.json ./frontend/
RUN npm ci --workspace frontend

COPY ./frontend ./frontend
CMD [ "npm","run","dev","--workspace","frontend" ]
