services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - ./cache/mysql-data:/var/lib/mysql
            - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        networks:
            - task_network
        # ports:
        #     - "3306:3306"
        #     - "33060:33060"
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        depends_on: [db]
        ports:
            - "3000:3000"
        networks:
            - task_network
        volumes:
          - ./backend:/app/backend 
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        depends_on: [backend]
        ports:
          - "5000:5000"
        networks:
           - task_network
        volumes:
          - ./frontend:/app/frontend
networks:
    task_network:
        driver: bridge
