services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - ./cache/mysql-data:/var/lib/mysql
            - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
    # backend:
    #     build: ./backend
    #     depends_on: db
    # frontend:
    #     build: ./frontend
    #     depends_on: backend
