FROM node:lts-slim

WORKDIR /app

COPY ./package.json ./
COPY ./package-lock.json ./
COPY ./backend/package.json ./backend/
RUN npm ci --workspace backend

COPY ./backend ./backend
CMD ["npm","run","dev:ts","--workspace","backend"]
